import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const fetchMeSomeBlogs = async () =>
  await fetch("https://639040c665ff4183110d7bdd.mockapi.io/blogs", {
    next: {
      revalidate: 5,
    },
  });

const useFetchMeSomeBlogs = () => {
  const [data, setData] = useState([] as any[]);
  useEffect(() => {
    fetchMeSomeBlogs()
      .then((res) => res.json())
      .then((json) => setData(json));
  }, []);
  return { data };
};

export default function Home() {
  const { data } = useFetchMeSomeBlogs();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data &&
          data.map((blogs, key) => {
            return (
              <div key={key}>
                <h1>{blogs.title}</h1>
                <p>{blogs.body}</p>
                <br />
              </div>
            );
          })}
      </main>
    </>
  );
}
